#
# Automatically generated file. DO NOT MODIFY
#

PRODUCT_SOONG_NAMESPACES += \
    vendor/nubia/nx619j

PRODUCT_COPY_FILES += \
    vendor/nubia/nx619j/proprietary/system/etc/permissions/audiosphere.xml:$(TARGET_COPY_OUT_SYSTEM)/etc/permissions/audiosphere.xml \
    vendor/nubia/nx619j/proprietary/vendor/etc/acdbdata/MTP/MTP_Bluetooth_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/MTP/MTP_Bluetooth_cal.acdb \
    vendor/nubia/nx619j/proprietary/vendor/etc/acdbdata/MTP/MTP_Codec_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/MTP/MTP_Codec_cal.acdb \
    vendor/nubia/nx619j/proprietary/vendor/etc/acdbdata/MTP/MTP_General_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/MTP/MTP_General_cal.acdb \
    vendor/nubia/nx619j/proprietary/vendor/etc/acdbdata/MTP/MTP_Global_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/MTP/MTP_Global_cal.acdb \
    vendor/nubia/nx619j/proprietary/vendor/etc/acdbdata/MTP/MTP_Handset_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/MTP/MTP_Handset_cal.acdb \
    vendor/nubia/nx619j/proprietary/vendor/etc/acdbdata/MTP/MTP_Hdmi_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/MTP/MTP_Hdmi_cal.acdb \
    vendor/nubia/nx619j/proprietary/vendor/etc/acdbdata/MTP/MTP_Headset_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/MTP/MTP_Headset_cal.acdb \
    vendor/nubia/nx619j/proprietary/vendor/etc/acdbdata/MTP/MTP_Speaker_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/MTP/MTP_Speaker_cal.acdb \
    vendor/nubia/nx619j/proprietary/vendor/etc/acdbdata/MTP/workspaceFile.qwsp:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/MTP/workspaceFile.qwsp \
    vendor/nubia/nx619j/proprietary/vendor/etc/acdbdata/adsp_avs_config.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/adsp_avs_config.acdb \
    vendor/nubia/nx619j/proprietary/vendor/etc/camera/SceneParamFile:$(TARGET_COPY_OUT_VENDOR)/etc/camera/SceneParamFile \
    vendor/nubia/nx619j/proprietary/vendor/etc/camera/SceneParamFile-320:$(TARGET_COPY_OUT_VENDOR)/etc/camera/SceneParamFile-320 \
    vendor/nubia/nx619j/proprietary/vendor/etc/camera/SceneParamFile-430:$(TARGET_COPY_OUT_VENDOR)/etc/camera/SceneParamFile-430 \
    vendor/nubia/nx619j/proprietary/vendor/etc/camera/camxoverridesettings.txt:$(TARGET_COPY_OUT_VENDOR)/etc/camera/camxoverridesettings.txt \
    vendor/nubia/nx619j/proprietary/vendor/etc/camera/icon/Thumbs.db:$(TARGET_COPY_OUT_VENDOR)/etc/camera/icon/Thumbs.db \
    vendor/nubia/nx619j/proprietary/vendor/etc/camera/icon/changes_small.png:$(TARGET_COPY_OUT_VENDOR)/etc/camera/icon/changes_small.png \
    vendor/nubia/nx619j/proprietary/vendor/etc/camera/icon/effect_lomo.png:$(TARGET_COPY_OUT_VENDOR)/etc/camera/icon/effect_lomo.png \
    vendor/nubia/nx619j/proprietary/vendor/etc/camera/icon/noise.png:$(TARGET_COPY_OUT_VENDOR)/etc/camera/icon/noise.png \
    vendor/nubia/nx619j/proprietary/vendor/etc/camera/icon/oldfilmdust.png:$(TARGET_COPY_OUT_VENDOR)/etc/camera/icon/oldfilmdust.png \
    vendor/nubia/nx619j/proprietary/vendor/etc/camera/icon/oldfilmscratches.png:$(TARGET_COPY_OUT_VENDOR)/etc/camera/icon/oldfilmscratches.png \
    vendor/nubia/nx619j/proprietary/vendor/etc/camera/icon/red2green.png:$(TARGET_COPY_OUT_VENDOR)/etc/camera/icon/red2green.png \
    vendor/nubia/nx619j/proprietary/vendor/etc/camera/icon/red2green_r.png:$(TARGET_COPY_OUT_VENDOR)/etc/camera/icon/red2green_r.png \
    vendor/nubia/nx619j/proprietary/vendor/etc/camera/icon/sucai0.png:$(TARGET_COPY_OUT_VENDOR)/etc/camera/icon/sucai0.png \
    vendor/nubia/nx619j/proprietary/vendor/etc/camera/icon/sucai0_r.png:$(TARGET_COPY_OUT_VENDOR)/etc/camera/icon/sucai0_r.png \
    vendor/nubia/nx619j/proprietary/vendor/etc/camera/icon/sucai3.png:$(TARGET_COPY_OUT_VENDOR)/etc/camera/icon/sucai3.png \
    vendor/nubia/nx619j/proprietary/vendor/etc/camera/icon/vignette.png:$(TARGET_COPY_OUT_VENDOR)/etc/camera/icon/vignette.png \
    vendor/nubia/nx619j/proprietary/vendor/etc/camera/icon/water_mark_drawable.argb:$(TARGET_COPY_OUT_VENDOR)/etc/camera/icon/water_mark_drawable.argb \
    vendor/nubia/nx619j/proprietary/vendor/etc/camera/icon/water_mark_drawable_black.argb:$(TARGET_COPY_OUT_VENDOR)/etc/camera/icon/water_mark_drawable_black.argb \
    vendor/nubia/nx619j/proprietary/vendor/etc/camera/icon/water_mark_drawable_white.argb:$(TARGET_COPY_OUT_VENDOR)/etc/camera/icon/water_mark_drawable_white.argb \
    vendor/nubia/nx619j/proprietary/vendor/etc/init/android.hardware.gatekeeper@1.0-service-qti.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.gatekeeper@1.0-service-qti.rc \
    vendor/nubia/nx619j/proprietary/vendor/etc/init/android.hardware.keymaster@4.0-service-qti.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.keymaster@4.0-service-qti.rc \
    vendor/nubia/nx619j/proprietary/vendor/etc/qdcm_calib_data_Dual_nt35597_video_mode_dsi_truly_panel_without_DSC.xml:$(TARGET_COPY_OUT_VENDOR)/etc/qdcm_calib_data_Dual_nt35597_video_mode_dsi_truly_panel_without_DSC.xml \
    vendor/nubia/nx619j/proprietary/vendor/etc/qdcm_calib_data_Sharp_4k_cmd_mode_dsc_dsi_panel.xml:$(TARGET_COPY_OUT_VENDOR)/etc/qdcm_calib_data_Sharp_4k_cmd_mode_dsc_dsi_panel.xml \
    vendor/nubia/nx619j/proprietary/vendor/etc/qdcm_calib_data_jdi_td4310_1080_2160_5p99_video_dsi_panel.xml:$(TARGET_COPY_OUT_VENDOR)/etc/qdcm_calib_data_jdi_td4310_1080_2160_5p99_video_dsi_panel.xml \
    vendor/nubia/nx619j/proprietary/vendor/etc/qdcm_calib_data_nt35597_cmd_mode_dsi_truly_panel_with_DSC.xml:$(TARGET_COPY_OUT_VENDOR)/etc/qdcm_calib_data_nt35597_cmd_mode_dsi_truly_panel_with_DSC.xml \
    vendor/nubia/nx619j/proprietary/vendor/etc/qdcm_calib_data_nt35597_video_mode_dsi_truly_panel_with_DSC.xml:$(TARGET_COPY_OUT_VENDOR)/etc/qdcm_calib_data_nt35597_video_mode_dsi_truly_panel_with_DSC.xml \
    vendor/nubia/nx619j/proprietary/vendor/etc/sensors/config/ak991x_dri_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/ak991x_dri_0.json \
    vendor/nubia/nx619j/proprietary/vendor/etc/sensors/config/bma2x2_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/bma2x2_0.json \
    vendor/nubia/nx619j/proprietary/vendor/etc/sensors/config/bme680_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/bme680_0.json \
    vendor/nubia/nx619j/proprietary/vendor/etc/sensors/config/bmg160_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/bmg160_0.json \
    vendor/nubia/nx619j/proprietary/vendor/etc/sensors/config/bmi160_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/bmi160_0.json \
    vendor/nubia/nx619j/proprietary/vendor/etc/sensors/config/bmm150_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/bmm150_0.json \
    vendor/nubia/nx619j/proprietary/vendor/etc/sensors/config/bmp285_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/bmp285_0.json \
    vendor/nubia/nx619j/proprietary/vendor/etc/sensors/config/bu52053nvx_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/bu52053nvx_0.json \
    vendor/nubia/nx619j/proprietary/vendor/etc/sensors/config/cm3526_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/cm3526_0.json \
    vendor/nubia/nx619j/proprietary/vendor/etc/sensors/config/config_list.txt:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/config_list.txt \
    vendor/nubia/nx619j/proprietary/vendor/etc/sensors/config/default_sensors.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/default_sensors.json \
    vendor/nubia/nx619j/proprietary/vendor/etc/sensors/config/dps368_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/dps368_0.json \
    vendor/nubia/nx619j/proprietary/vendor/etc/sensors/config/icm206xx_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/icm206xx_0.json \
    vendor/nubia/nx619j/proprietary/vendor/etc/sensors/config/lsm6ds3_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/lsm6ds3_0.json \
    vendor/nubia/nx619j/proprietary/vendor/etc/sensors/config/lsm6ds3c_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/lsm6ds3c_0.json \
    vendor/nubia/nx619j/proprietary/vendor/etc/sensors/config/lsm6dsm_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/lsm6dsm_0.json \
    vendor/nubia/nx619j/proprietary/vendor/etc/sensors/config/lsm6dsm_0_16g.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/lsm6dsm_0_16g.json \
    vendor/nubia/nx619j/proprietary/vendor/etc/sensors/config/lsm6dsm_0_8g.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/lsm6dsm_0_8g.json \
    vendor/nubia/nx619j/proprietary/vendor/etc/sensors/config/lsm6dso_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/lsm6dso_0.json \
    vendor/nubia/nx619j/proprietary/vendor/etc/sensors/config/lsm6dso_0_16g.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/lsm6dso_0_16g.json \
    vendor/nubia/nx619j/proprietary/vendor/etc/sensors/config/lsm6dso_0_8g.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/lsm6dso_0_8g.json \
    vendor/nubia/nx619j/proprietary/vendor/etc/sensors/config/ltr308_0_on_change.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/ltr308_0_on_change.json \
    vendor/nubia/nx619j/proprietary/vendor/etc/sensors/config/pah_8011_0_platform.ppg_enable_ex_1.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/pah_8011_0_platform.ppg_enable_ex_1.json \
    vendor/nubia/nx619j/proprietary/vendor/etc/sensors/config/pah_8011_0_platform.ppg_enable_ex_2.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/pah_8011_0_platform.ppg_enable_ex_2.json \
    vendor/nubia/nx619j/proprietary/vendor/etc/sensors/config/rpr0521rs_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/rpr0521rs_0.json \
    vendor/nubia/nx619j/proprietary/vendor/etc/sensors/config/sdm845_ak991x_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sdm845_ak991x_0.json \
    vendor/nubia/nx619j/proprietary/vendor/etc/sensors/config/sdm845_icm206xx_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sdm845_icm206xx_0.json \
    vendor/nubia/nx619j/proprietary/vendor/etc/sensors/config/sdm845_lsm6ds3c_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sdm845_lsm6ds3c_0.json \
    vendor/nubia/nx619j/proprietary/vendor/etc/sensors/config/sdm845_power_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sdm845_power_0.json \
    vendor/nubia/nx619j/proprietary/vendor/etc/sensors/config/sdm845_qrd_power_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sdm845_qrd_power_0.json \
    vendor/nubia/nx619j/proprietary/vendor/etc/sensors/config/sdm845_qvr_ak991x_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sdm845_qvr_ak991x_0.json \
    vendor/nubia/nx619j/proprietary/vendor/etc/sensors/config/sdm845_shtw2_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sdm845_shtw2_0.json \
    vendor/nubia/nx619j/proprietary/vendor/etc/sensors/config/sdm845_svr_rpr0521rs_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sdm845_svr_rpr0521rs_0.json \
    vendor/nubia/nx619j/proprietary/vendor/etc/sensors/config/shtw2_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/shtw2_0.json \
    vendor/nubia/nx619j/proprietary/vendor/etc/sensors/config/sns_amd.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_amd.json \
    vendor/nubia/nx619j/proprietary/vendor/etc/sensors/config/sns_amd_sw_disabled.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_amd_sw_disabled.json \
    vendor/nubia/nx619j/proprietary/vendor/etc/sensors/config/sns_amd_sw_enabled.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_amd_sw_enabled.json \
    vendor/nubia/nx619j/proprietary/vendor/etc/sensors/config/sns_aont.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_aont.json \
    vendor/nubia/nx619j/proprietary/vendor/etc/sensors/config/sns_basic_gestures.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_basic_gestures.json \
    vendor/nubia/nx619j/proprietary/vendor/etc/sensors/config/sns_bring_to_ear.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_bring_to_ear.json \
    vendor/nubia/nx619j/proprietary/vendor/etc/sensors/config/sns_ccd.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_ccd.json \
    vendor/nubia/nx619j/proprietary/vendor/etc/sensors/config/sns_cm.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_cm.json \
    vendor/nubia/nx619j/proprietary/vendor/etc/sensors/config/sns_dae.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_dae.json \
    vendor/nubia/nx619j/proprietary/vendor/etc/sensors/config/sns_device_orient.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_device_orient.json \
    vendor/nubia/nx619j/proprietary/vendor/etc/sensors/config/sns_diag_filter.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_diag_filter.json \
    vendor/nubia/nx619j/proprietary/vendor/etc/sensors/config/sns_distance_bound.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_distance_bound.json \
    vendor/nubia/nx619j/proprietary/vendor/etc/sensors/config/sns_dpc.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_dpc.json \
    vendor/nubia/nx619j/proprietary/vendor/etc/sensors/config/sns_facing.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_facing.json \
    vendor/nubia/nx619j/proprietary/vendor/etc/sensors/config/sns_fmv.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_fmv.json \
    vendor/nubia/nx619j/proprietary/vendor/etc/sensors/config/sns_geomag_rv.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_geomag_rv.json \
    vendor/nubia/nx619j/proprietary/vendor/etc/sensors/config/sns_gyro_cal.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_gyro_cal.json \
    vendor/nubia/nx619j/proprietary/vendor/etc/sensors/config/sns_heart_rate.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_heart_rate.json \
    vendor/nubia/nx619j/proprietary/vendor/etc/sensors/config/sns_mag_cal.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_mag_cal.json \
    vendor/nubia/nx619j/proprietary/vendor/etc/sensors/config/sns_multishake.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_multishake.json \
    vendor/nubia/nx619j/proprietary/vendor/etc/sensors/config/sns_pedometer.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_pedometer.json \
    vendor/nubia/nx619j/proprietary/vendor/etc/sensors/config/sns_rmd.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_rmd.json \
    vendor/nubia/nx619j/proprietary/vendor/etc/sensors/config/sns_rotv.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_rotv.json \
    vendor/nubia/nx619j/proprietary/vendor/etc/sensors/config/sns_smd.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_smd.json \
    vendor/nubia/nx619j/proprietary/vendor/etc/sensors/config/sns_tilt.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_tilt.json \
    vendor/nubia/nx619j/proprietary/vendor/etc/sensors/config/sns_tilt_sw_disabled.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_tilt_sw_disabled.json \
    vendor/nubia/nx619j/proprietary/vendor/etc/sensors/config/sns_tilt_sw_enabled.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_tilt_sw_enabled.json \
    vendor/nubia/nx619j/proprietary/vendor/etc/sensors/config/sns_tilt_to_wake.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_tilt_to_wake.json \
    vendor/nubia/nx619j/proprietary/vendor/etc/sensors/config/sns_wrist_pedo.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_wrist_pedo.json \
    vendor/nubia/nx619j/proprietary/vendor/etc/sensors/config/tmd2725.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/tmd2725.json \
    vendor/nubia/nx619j/proprietary/vendor/etc/sensors/config/tmx4903.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/tmx4903.json \
    vendor/nubia/nx619j/proprietary/vendor/etc/sensors/hals.conf:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/hals.conf \
    vendor/nubia/nx619j/proprietary/vendor/etc/thermal-engine.conf:$(TARGET_COPY_OUT_VENDOR)/etc/thermal-engine.conf \
    vendor/nubia/nx619j/proprietary/vendor/firmware/CAMERA_ICP.elf:$(TARGET_COPY_OUT_VENDOR)/firmware/CAMERA_ICP.elf \
    vendor/nubia/nx619j/proprietary/vendor/firmware/a630_gmu.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/a630_gmu.bin \
    vendor/nubia/nx619j/proprietary/vendor/firmware/a630_sqe.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/a630_sqe.fw \
    vendor/nubia/nx619j/proprietary/vendor/firmware/a630_zap.b00:$(TARGET_COPY_OUT_VENDOR)/firmware/a630_zap.b00 \
    vendor/nubia/nx619j/proprietary/vendor/firmware/a630_zap.b01:$(TARGET_COPY_OUT_VENDOR)/firmware/a630_zap.b01 \
    vendor/nubia/nx619j/proprietary/vendor/firmware/a630_zap.b02:$(TARGET_COPY_OUT_VENDOR)/firmware/a630_zap.b02 \
    vendor/nubia/nx619j/proprietary/vendor/firmware/a630_zap.elf:$(TARGET_COPY_OUT_VENDOR)/firmware/a630_zap.elf \
    vendor/nubia/nx619j/proprietary/vendor/firmware/a630_zap.mdt:$(TARGET_COPY_OUT_VENDOR)/firmware/a630_zap.mdt \
    vendor/nubia/nx619j/proprietary/vendor/firmware/aw22xxx_cfg_0.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw22xxx_cfg_0.bin \
    vendor/nubia/nx619j/proprietary/vendor/firmware/aw22xxx_cfg_1.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw22xxx_cfg_1.bin \
    vendor/nubia/nx619j/proprietary/vendor/firmware/aw22xxx_cfg_10.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw22xxx_cfg_10.bin \
    vendor/nubia/nx619j/proprietary/vendor/firmware/aw22xxx_cfg_11.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw22xxx_cfg_11.bin \
    vendor/nubia/nx619j/proprietary/vendor/firmware/aw22xxx_cfg_12.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw22xxx_cfg_12.bin \
    vendor/nubia/nx619j/proprietary/vendor/firmware/aw22xxx_cfg_13.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw22xxx_cfg_13.bin \
    vendor/nubia/nx619j/proprietary/vendor/firmware/aw22xxx_cfg_14.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw22xxx_cfg_14.bin \
    vendor/nubia/nx619j/proprietary/vendor/firmware/aw22xxx_cfg_15.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw22xxx_cfg_15.bin \
    vendor/nubia/nx619j/proprietary/vendor/firmware/aw22xxx_cfg_16.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw22xxx_cfg_16.bin \
    vendor/nubia/nx619j/proprietary/vendor/firmware/aw22xxx_cfg_17.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw22xxx_cfg_17.bin \
    vendor/nubia/nx619j/proprietary/vendor/firmware/aw22xxx_cfg_18.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw22xxx_cfg_18.bin \
    vendor/nubia/nx619j/proprietary/vendor/firmware/aw22xxx_cfg_19.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw22xxx_cfg_19.bin \
    vendor/nubia/nx619j/proprietary/vendor/firmware/aw22xxx_cfg_1a.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw22xxx_cfg_1a.bin \
    vendor/nubia/nx619j/proprietary/vendor/firmware/aw22xxx_cfg_1b.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw22xxx_cfg_1b.bin \
    vendor/nubia/nx619j/proprietary/vendor/firmware/aw22xxx_cfg_1c.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw22xxx_cfg_1c.bin \
    vendor/nubia/nx619j/proprietary/vendor/firmware/aw22xxx_cfg_1d.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw22xxx_cfg_1d.bin \
    vendor/nubia/nx619j/proprietary/vendor/firmware/aw22xxx_cfg_1e.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw22xxx_cfg_1e.bin \
    vendor/nubia/nx619j/proprietary/vendor/firmware/aw22xxx_cfg_1f.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw22xxx_cfg_1f.bin \
    vendor/nubia/nx619j/proprietary/vendor/firmware/aw22xxx_cfg_2.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw22xxx_cfg_2.bin \
    vendor/nubia/nx619j/proprietary/vendor/firmware/aw22xxx_cfg_20.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw22xxx_cfg_20.bin \
    vendor/nubia/nx619j/proprietary/vendor/firmware/aw22xxx_cfg_21.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw22xxx_cfg_21.bin \
    vendor/nubia/nx619j/proprietary/vendor/firmware/aw22xxx_cfg_22.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw22xxx_cfg_22.bin \
    vendor/nubia/nx619j/proprietary/vendor/firmware/aw22xxx_cfg_23.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw22xxx_cfg_23.bin \
    vendor/nubia/nx619j/proprietary/vendor/firmware/aw22xxx_cfg_24.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw22xxx_cfg_24.bin \
    vendor/nubia/nx619j/proprietary/vendor/firmware/aw22xxx_cfg_25.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw22xxx_cfg_25.bin \
    vendor/nubia/nx619j/proprietary/vendor/firmware/aw22xxx_cfg_26.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw22xxx_cfg_26.bin \
    vendor/nubia/nx619j/proprietary/vendor/firmware/aw22xxx_cfg_27.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw22xxx_cfg_27.bin \
    vendor/nubia/nx619j/proprietary/vendor/firmware/aw22xxx_cfg_28.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw22xxx_cfg_28.bin \
    vendor/nubia/nx619j/proprietary/vendor/firmware/aw22xxx_cfg_29.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw22xxx_cfg_29.bin \
    vendor/nubia/nx619j/proprietary/vendor/firmware/aw22xxx_cfg_2a.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw22xxx_cfg_2a.bin \
    vendor/nubia/nx619j/proprietary/vendor/firmware/aw22xxx_cfg_2b.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw22xxx_cfg_2b.bin \
    vendor/nubia/nx619j/proprietary/vendor/firmware/aw22xxx_cfg_2c.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw22xxx_cfg_2c.bin \
    vendor/nubia/nx619j/proprietary/vendor/firmware/aw22xxx_cfg_3.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw22xxx_cfg_3.bin \
    vendor/nubia/nx619j/proprietary/vendor/firmware/aw22xxx_cfg_33.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw22xxx_cfg_33.bin \
    vendor/nubia/nx619j/proprietary/vendor/firmware/aw22xxx_cfg_34.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw22xxx_cfg_34.bin \
    vendor/nubia/nx619j/proprietary/vendor/firmware/aw22xxx_cfg_35.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw22xxx_cfg_35.bin \
    vendor/nubia/nx619j/proprietary/vendor/firmware/aw22xxx_cfg_36.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw22xxx_cfg_36.bin \
    vendor/nubia/nx619j/proprietary/vendor/firmware/aw22xxx_cfg_37.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw22xxx_cfg_37.bin \
    vendor/nubia/nx619j/proprietary/vendor/firmware/aw22xxx_cfg_4.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw22xxx_cfg_4.bin \
    vendor/nubia/nx619j/proprietary/vendor/firmware/aw22xxx_cfg_5.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw22xxx_cfg_5.bin \
    vendor/nubia/nx619j/proprietary/vendor/firmware/aw22xxx_cfg_6.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw22xxx_cfg_6.bin \
    vendor/nubia/nx619j/proprietary/vendor/firmware/aw22xxx_cfg_7.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw22xxx_cfg_7.bin \
    vendor/nubia/nx619j/proprietary/vendor/firmware/aw22xxx_cfg_8.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw22xxx_cfg_8.bin \
    vendor/nubia/nx619j/proprietary/vendor/firmware/aw22xxx_cfg_9.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw22xxx_cfg_9.bin \
    vendor/nubia/nx619j/proprietary/vendor/firmware/aw22xxx_cfg_a.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw22xxx_cfg_a.bin \
    vendor/nubia/nx619j/proprietary/vendor/firmware/aw22xxx_cfg_b.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw22xxx_cfg_b.bin \
    vendor/nubia/nx619j/proprietary/vendor/firmware/aw22xxx_cfg_c.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw22xxx_cfg_c.bin \
    vendor/nubia/nx619j/proprietary/vendor/firmware/aw22xxx_cfg_d.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw22xxx_cfg_d.bin \
    vendor/nubia/nx619j/proprietary/vendor/firmware/aw22xxx_cfg_e.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw22xxx_cfg_e.bin \
    vendor/nubia/nx619j/proprietary/vendor/firmware/aw22xxx_cfg_f.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw22xxx_cfg_f.bin \
    vendor/nubia/nx619j/proprietary/vendor/firmware/aw22xxx_fw.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw22xxx_fw.bin \
    vendor/nubia/nx619j/proprietary/vendor/firmware/leia_pfp_470.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/leia_pfp_470.fw \
    vendor/nubia/nx619j/proprietary/vendor/firmware/leia_pm4_470.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/leia_pm4_470.fw \
    vendor/nubia/nx619j/proprietary/vendor/firmware/nubia_tp_jdi_fw.img:$(TARGET_COPY_OUT_VENDOR)/firmware/nubia_tp_jdi_fw.img \
    vendor/nubia/nx619j/proprietary/vendor/firmware/tfa98xx.cnt:$(TARGET_COPY_OUT_VENDOR)/firmware/tfa98xx.cnt \
    vendor/nubia/nx619j/proprietary/vendor/firmware/tfa9xxx.cnt:$(TARGET_COPY_OUT_VENDOR)/firmware/tfa9xxx.cnt \
    vendor/nubia/nx619j/proprietary/vendor/lib/camera/com.qti.sensormodule.nubia_imx499.bin:$(TARGET_COPY_OUT_VENDOR)/lib/camera/com.qti.sensormodule.nubia_imx499.bin \
    vendor/nubia/nx619j/proprietary/vendor/lib/camera/com.qti.sensormodule.nubia_nx619_imx519.bin:$(TARGET_COPY_OUT_VENDOR)/lib/camera/com.qti.sensormodule.nubia_nx619_imx519.bin \
    vendor/nubia/nx619j/proprietary/vendor/lib/camera/com.qti.sensormodule.nubia_nx619_ov8856.bin:$(TARGET_COPY_OUT_VENDOR)/lib/camera/com.qti.sensormodule.nubia_nx619_ov8856.bin \
    vendor/nubia/nx619j/proprietary/vendor/lib/camera/com.qti.sensormodule.nubia_s5k2x7.bin:$(TARGET_COPY_OUT_VENDOR)/lib/camera/com.qti.sensormodule.nubia_s5k2x7.bin \
    vendor/nubia/nx619j/proprietary/vendor/lib/camera/com.qti.sensormodule.sony_imx000.bin:$(TARGET_COPY_OUT_VENDOR)/lib/camera/com.qti.sensormodule.sony_imx000.bin \
    vendor/nubia/nx619j/proprietary/vendor/lib/camera/com.qti.tuned.default.bin:$(TARGET_COPY_OUT_VENDOR)/lib/camera/com.qti.tuned.default.bin \
    vendor/nubia/nx619j/proprietary/vendor/lib/camera/com.qti.tuned.nubia_imx499.bin:$(TARGET_COPY_OUT_VENDOR)/lib/camera/com.qti.tuned.nubia_imx499.bin \
    vendor/nubia/nx619j/proprietary/vendor/lib/camera/com.qti.tuned.nubia_imx519front.bin:$(TARGET_COPY_OUT_VENDOR)/lib/camera/com.qti.tuned.nubia_imx519front.bin \
    vendor/nubia/nx619j/proprietary/vendor/lib/camera/com.qti.tuned.nubia_nx619_imx519.bin:$(TARGET_COPY_OUT_VENDOR)/lib/camera/com.qti.tuned.nubia_nx619_imx519.bin \
    vendor/nubia/nx619j/proprietary/vendor/lib/camera/com.qti.tuned.nubia_nx619_ov8856.bin:$(TARGET_COPY_OUT_VENDOR)/lib/camera/com.qti.tuned.nubia_nx619_ov8856.bin \
    vendor/nubia/nx619j/proprietary/vendor/lib/camera/com.qti.tuned.nubia_s5k2x7.bin:$(TARGET_COPY_OUT_VENDOR)/lib/camera/com.qti.tuned.nubia_s5k2x7.bin \
    vendor/nubia/nx619j/proprietary/vendor/lib/camera/fdconfigpreview.bin:$(TARGET_COPY_OUT_VENDOR)/lib/camera/fdconfigpreview.bin \
    vendor/nubia/nx619j/proprietary/vendor/lib/camera/fdconfigpreviewlite.bin:$(TARGET_COPY_OUT_VENDOR)/lib/camera/fdconfigpreviewlite.bin \
    vendor/nubia/nx619j/proprietary/vendor/lib/camera/fdconfigvideo.bin:$(TARGET_COPY_OUT_VENDOR)/lib/camera/fdconfigvideo.bin \
    vendor/nubia/nx619j/proprietary/vendor/lib/camera/fdconfigvideolite.bin:$(TARGET_COPY_OUT_VENDOR)/lib/camera/fdconfigvideolite.bin \
    vendor/nubia/nx619j/proprietary/vendor/lib/camera/titan17x_usecases.bin:$(TARGET_COPY_OUT_VENDOR)/lib/camera/titan17x_usecases.bin

PRODUCT_PACKAGES += \
    libthermalclient \
    com.qti.sensor.imx000 \
    com.qti.sensor.imx318 \
    com.qti.sensor.imx362 \
    com.qti.sensor.imx499 \
    com.qti.sensor.imx519 \
    com.qti.sensor.nx619_imx519 \
    com.qti.sensor.nx619_ov8856 \
    com.qti.sensor.ov12a10 \
    com.qti.sensor.ov13855 \
    com.qti.sensor.ov13880 \
    com.qti.sensor.ov8856 \
    com.qti.sensor.s5k2x7 \
    com.arcsoft.node.capturebokeh \
    com.arcsoft.node.realtimebokeh \
    com.nubia.node.nubiaalgorithm \
    com.nubia.node.nubiahdr \
    com.nubia.node.realtimeaicamera \
    com.nubia.node.realtimealgorithm \
    com.qti.eisv2 \
    com.qti.eisv3 \
    com.qti.hvx.addconstant \
    com.qti.hvx.binning \
    com.qti.node.dummyrtb \
    com.qti.node.dummysat \
    com.qti.node.eisv2 \
    com.qti.node.eisv3 \
    com.qti.node.gpu \
    com.qti.node.memcpy \
    com.qti.node.remosaic \
    com.qti.node.stich \
    com.qti.node.swregistration \
    com.qti.stats.aec \
    com.qti.stats.af \
    com.qti.stats.afd \
    com.qti.stats.asd \
    com.qti.stats.awb \
    com.qti.stats.awbwrapper \
    com.qti.stats.pdlib \
    com.qti.stats.pdlibsony \
    com.qti.stats.pdlibwrapper \
    com.qtistatic.stats.aec \
    com.qtistatic.stats.af \
    com.qtistatic.stats.awb \
    com.qtistatic.stats.pdlib \
    audio.primary.sdm845 \
    camera.qcom \
    com.qti.chi.override \
    libacdb-fts \
    libacdbloader \
    libacdbrtac \
    libadiertac \
    libadm \
    libarcsoft_beautyshot \
    libarcsoft_high_dynamic_range \
    libaudcal \
    libaudio_log_utils \
    libaudioalsa \
    libaudioparsers \
    libcamxfdalgov7 \
    libcamxfdengine \
    libcamxstatscore \
    libcamxtintlessalgo \
    libcom.nubia.chinodenubiautils \
    libcom.qti.chinodeutils \
    libcsd-client \
    libdts-eagle-shared \
    libmdsprpc \
    libmmcamera_faceproc \
    libmmcamera_faceproc2 \
    libmpbase \
    libqtigef \
    libswregistrationalgo \
    libtinycompress_vendor \
    libasphere \
    libdtsaudio \
    libqcbassboost \
    libqcreverb \
    libqcvirt \
    libshoebox \
    libvolumelistener \
    android.hardware.gatekeeper@1.0-impl-qti \
    fingerprint.goodix.sdm845 \
    fingerprint.silead.spec.sdm845 \
    libgf_ca \
    libgf_hal \
    libgoodixhwfingerprint \
    libkeymasterdeviceutils \
    libkeymasterprovision \
    libkeymasterutils \
    libqtikeymaster4 \
    libsl_fp_impl \
    libteeclientjni \
    sensors.oem \
    sensors.ssc \
    vendor.goodix.hardware.biometrics.fingerprint@2.1 \
    vendor.nubia.ifaa@1.0-impl \
    vendor.nubia.ifaa@1.0 \
    vendor.qti.hardware.fingerprint@1.0 \
    audiosphere \
    hvdcp_opti \
    android.hardware.gatekeeper@1.0-service-qti \
    android.hardware.keymaster@4.0-service-qti \
    thermal-engine
